### ISSUE TITLE
No Export Button on Registry Page

### ISSUE THREAD

**Issue by kidtrini** [mrdave-dev/amazon-baby-registry-gift-list-export#31]
Hello,

Thanks for your work.  I tried to run the script on Safari and Chrome but there is not an export button on the registry page.   Not sure if Amazon changed their page and script does not function anymore.  Is there anyway you can check to see if the script needs to be updated?  

Thanks,
SD

**Comment by kidtrini** [comment]
Thanks for your help.  Appreciate the work. 
SD

**Comment by rosemaryhua** [comment]
Any update? I just tried and I don't see the export button either. Thank you so much by the way... super helpful!

**Comment by mrdave-dev** [comment]
Hey all! Sorry, work has had me busy with year-end commitments. Here's a proposed fix. PLEASE let me know if this works for you; Amazon can sometimes use different UIs for different users and countries. 

https://github.com/mrdave-dev/amazon-baby-registry-gift-list-export/pull/32

Here's the user script: https://github.com/mrdave-dev/amazon-baby-registry-gift-list-export/blob/mrdave/20241210-fix/gift-list-export.user.js

**Comment by mrdave-dev** [comment]
(tagging @rosemaryhua @kidtrini)

**Comment by mrdave-dev** [comment]
I've merged in a fix. Please let me know if a problem still exists.
